### PR TITLE
Reduce startup time and overhead by using Moo instead of Moose

### PR DESCRIPTION
**Pull request by mjgardner**
I've changed this over to use Moo rather than Moose, as well as better use of attributes and method modifiers. Also ran tidyall on the source since there was a .tidyallrc in the repo.

### CODE REVIEW

**Comment by oalders** [comment]
Thanks for this!  I had actually forgotten it was using Moose, so this is pretty handy as I wanted to use this module in another CPAN dist that I'm trying to avoid Moose deps for.  :)

**Comment by oalders** [comment]
New version on its way to CPAN.

**Comment by oalders** [comment]
Haven't had time to look into it, but it feels like there are more test failures in this new version: http://www.cpantesters.org/distro/W/WWW-Mechanize-Cached.html?oncpan=1&distmat=1&version=1.45  About 13% fail rate on this version vs 3% on the previous version.

**Comment by mjgardner** [comment]
About half are, I'll look into it since it's a Moo attribute issue:
```
Invalid default '' for WWW::Mechanize::Cached->is_cached not a coderef or a non-ref or code-convertible object
```
Others are Storable issues, not sure how to address:
```
Double size is not compatible
```

**Comment by mjgardner** [comment]
It's an issue with using `undef` as a default in older versions of Moo that was fixed in 1.004_003. I will adjust the prereqs.

**Comment by mjgardner** [comment]
See PR #8

**Comment by oalders** [comment]
Thanks for looking into the newer failures.  There's already an open ticket for the Storable failures.

**Pull request merged**
